# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    dataPath: '%kernel.project_dir%/data'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Command\:
        resource: '../src/Command/*'
        tags: ['console.command']

    App\Command\GetMessagesCommand:
        arguments:
            - '@App\Service\GoogleClientService'
            - '%dataPath%'
            - '@doctrine.orm.entity_manager'

    App\Command\OCRCommand:
        arguments:
            - '@Google\Cloud\Vision\VisionClient'
            - '%dataPath%'
            - '@doctrine.orm.entity_manager'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Repository\UserRepository:
        class: App\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['App\Entity\User']

    App\Service\GoogleClientService:
        arguments:
            - '%env(resolve:GOOGLE_CLIENT_ID)%'
            - '%env(resolve:GOOGLE_CLIENT_SECRET)%'
            - '%env(resolve:GOOGLE_REDIRECT_URI)%'
            - '%dataPath%'

    Google\Cloud\Vision\VisionClient:
        arguments: [keyFilePath: '%dataPath%/google_auth.json']
